import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { AppSidebar } from "@/components/app-sidebar";
import { ThemeProvider } from "@/components/theme-provider";
import { SidebarLayout, SidebarTrigger } from "@/components/ui/sidebar";
import { ThemeToggle } from "@/components/ui/theme-toggle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { cookies } = await import("next/headers");
  const isDev = process.env.NODE_ENV === "development";

  return (
    <html lang="en" suppressHydrationWarning={isDev}>
      <body className={`${inter.className}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarLayout
            defaultOpen={cookies().get("sidebar:state")?.value === "true"}
          >
            <AppSidebar />
            <main className="flex flex-1 flex-col p-2 transition-all duration-300 ease-in-out">
              <div className="h-full rounded-md border-2 border-dashed p-2">
                <SidebarTrigger />
                <ThemeToggle />
                {children}
              </div>
            </main>
          </SidebarLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}
